version: '3.8'

services:
  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  # Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=sports_store
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - NUVEMPAGO_CLIENT_ID=your_client_id
      - NUVEMPAGO_CLIENT_SECRET=your_client_secret
      - NUVEMPAGO_SANDBOX=true
      - MERCADOPAGO_PUBLIC_KEY=APP_USR-2cae30fc-494d-40dd-815d-1c2a5f7bc250
      - MERCADOPAGO_ACCESS_TOKEN=APP_USR-6504293319698934-102211-5d652799fa97a98bf607a8d5ab5c6813-2935832258
      - MERCADOPAGO_SANDBOX=true
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  # MySQL Database
  database:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=sports_store
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
    restart: unless-stopped

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - database

volumes:
  mysql_data: